<Tlacitko@Button>: #styl pro tlacitko
    font_size: 64

<Calculator>:
    #display: vstup
    #rows: 6
    rows: 7
    padding: 10
    spacing: 10
 
    BoxLayout: # display pro postup
        TextInput:
            id: vstup
            font_size: 64
            multiline: False
            disabled: True # zakaze psat do displeje
            halign: 'right' #text odkud kam
            valign: 'middle'

    BoxLayout: 
        TextInput: # vysledek, pohrát si s velikostí a hodit to pod sebe
            id: vystup
            font_size: 128
            multiline: False
            halign: 'right'
  
    BoxLayout: #zbytek, kdyztak to prehazim
        spacing: 10
        Tlacitko:
            text: "7"
            #on_press: vstup.text += self.text #vstup je to ID
            on_press: Calculator.Widget.tlacitka_cisla(7)
        Tlacitko:
            text: "8"
            on_press: vstup.text += self.text
        Tlacitko:
            text: "9"
            on_press: vstup.text += self.text
        Tlacitko:
            text: "+"
            on_press: vstup.text += self.text
  
    BoxLayout:
        spacing: 10
        Tlacitko:
            text: "4"
            on_press: vstup.text += self.text
        Tlacitko:
            text: "5"
            on_press: vstup.text += self.text
        Tlacitko:
            text: "6"
            on_press: vstup.text += self.text
        Tlacitko:
            text: "-"
            on_press: vstup.text += self.text
  
    BoxLayout:
        spacing: 10
        Tlacitko:
            text: "1"
            on_press: vstup.text += self.text
        Tlacitko:
            text: "2"
            on_press: vstup.text += self.text
        Tlacitko:
            text: "3"
            on_press: vstup.text += self.text
        Tlacitko:
            text: "*"
            on_press: vstup.text += self.text
  
    BoxLayout:
        spacing: 10
        Tlacitko:
            text: "AC"
            on_press: vstup.text = ""
        Tlacitko:
            text: "0"
            on_press: vstup.text += self.text
        Tlacitko:
            text: "="
            on_press: calculator.calculate(vstup.text)
        Tlacitko:
            text: "/"
            on_press: vstup.text += self.text
    
    BoxLayout:
        Tlacitko:
            font_size: 64
            text: "Vědecká kalkulačka"
            on_press: vstup.text = ""  
        Tlacitko:
            font_size: 64
            text: "Změnit barevný režim"
            on_press: