BoxLayout:
    orientation: "vertical"

    GridLayout:
        row: 3
        cols: 2

        Image:
            source: "./pan.jpg"
            size_hint_y: None
            size: 100,100
            allow_stretch: True
        Image:
            source: "./pan.jpg"
        Image:
            source: "./pan.jpg"
        # sloupec 2
        Image:
            source: "./pan.jpg"
        Image:
            source: "./pan.jpg"
        Image:
            source: "./pan.jpg"